volumes:
  data:
  export:

services:
  web:
    build: ./urbansoul-app
    container_name: urbansoul-app
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./urbansoul-app:/app

  api:
    build: ./urbansoul-api
    container_name: urbansoul-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - app

  postgres:
    image: docker.io/postgres:14-alpine
    container_name: urbansoul-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: urbansoul-pass
    volumes:
      - data:/var/lib/postgresql/data
      - export:/export
