services:

  web:
    build: ./urbansoul-app
    container_name: urbansoul-app
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./urbansoul-app:/app

  api:
    build: ./urbansoul-api
    container_name: urbansoul-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres.cefhcvahzzarrccvqhbq:[YOUR-PASSWORD]@aws-0-us-west-2.pooler.supabase.com:6543/postgres
    depends_on:
      - app

  postgres:
    image: postgres:15
    container_name: urbansoul-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: urbansoul-pass
      POSTGRES_DB: urbansoul-db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
